/**
 * Citibank Authenticator
 * Citibank Hackathon 2019 Authenticator
 *
 * OpenAPI spec version: 0.0.1
 * Contact: EMAIL
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.8
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
    if (typeof module === 'object' && module.exports) {
        // CommonJS-like environments that support module.exports, like Node.
        module.exports = factory(require('../ApiClient'));
    } else {
        // Browser globals (root is window)
        if (!root.CitibankAuthenticator) {
            root.CitibankAuthenticator = {};
        }
        root.CitibankAuthenticator.Principal = factory(root.CitibankAuthenticator.ApiClient);
    }
})(this, function(ApiClient) {
    'use strict';

    /**
     * The Principal model module.
     * @module model/Principal
     * @version 0.0.1
     */

    /**
     * Constructs a new <code>Principal</code>.
     * @alias module:model/Principal
     * @class
     */
    var exports = function() {
        var _this = this;
    };

    /**
     * Constructs a <code>Principal</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Principal} obj Optional instance to populate.
     * @return {module:model/Principal} The populated <code>Principal</code> instance.
     */
    exports.constructFromObject = function(data, obj) {
        if (data) {
            obj = obj || new exports();

            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }

            if (data.hasOwnProperty('authorities')) {
                obj['authorities'] = ApiClient.convertToType(data['authorities'], 'Array');
            }
        }
        return obj;
    };

    /**
     * @member {String} name
     */
    exports.prototype['name'] = undefined;

    return exports;
});
