/**
 * Citibank Communicator
 * Email Notifications Sender
 *
 * OpenAPI spec version: 0.0.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.8
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof module === "object" && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require("../ApiClient"));
  } else {
    // Browser globals (root is window)
    if (!root.CitibankCommunicator) {
      root.CitibankCommunicator = {};
    }
    root.CitibankCommunicator.FullSubscriptionApi = factory(
      root.CitibankCommunicator.ApiClient
    );
  }
})(this, function(ApiClient) {
  "use strict";

  /**
   * FullSubscription service.
   * @module api/FullSubscriptionApi
   * @version 0.0.1
   */

  /**
   * Constructs a new FullSubscriptionApi.
   * @alias module:api/FullSubscriptionApi
   * @class
   * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
   * default to {@link module:ApiClient#instance} if unspecified.
   */
  var exports = function(apiClient) {
    this.apiClient = apiClient || ApiClient.instance;

    /**
     * Callback function to receive the result of the eventsFullSubscriptionDelete operation.
     * @callback module:api/FullSubscriptionApi~eventsFullSubscriptionDeleteCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Unsubscribe user from event notification
     * Lorem Ipsum Dolor Sit Amet
     * @param {Number} eventId The event ID
     * @param {Number} userId The user ID
     * @param {module:api/FullSubscriptionApi~eventsFullSubscriptionDeleteCallback} callback The callback function, accepting three arguments: error, data, response
     */
    this.eventsFullSubscriptionDelete = function(eventId, userId, callback) {
      var postBody = null;

      // verify the required parameter 'eventId' is set
      if (eventId === undefined || eventId === null) {
        throw new Error(
          "Missing the required parameter 'eventId' when calling eventsFullSubscriptionDelete"
        );
      }

      // verify the required parameter 'userId' is set
      if (userId === undefined || userId === null) {
        throw new Error(
          "Missing the required parameter 'userId' when calling eventsFullSubscriptionDelete"
        );
      }

      var pathParams = {};
      var queryParams = {
        eventId: eventId,
        userId: userId
      };
      var collectionQueryParams = {};
      var headerParams = {};
      var formParams = {};

      var authNames = [];
      var contentTypes = [];
      var accepts = [];
      var returnType = null;

      return this.apiClient.callApi(
        "/events/fullSubscription",
        "DELETE",
        pathParams,
        queryParams,
        collectionQueryParams,
        headerParams,
        formParams,
        postBody,
        authNames,
        contentTypes,
        accepts,
        returnType,
        callback
      );
    };

    /**
     * Callback function to receive the result of the eventsFullSubscriptionPost operation.
     * @callback module:api/FullSubscriptionApi~eventsFullSubscriptionPostCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Subscribe user to event notification
     * Lorem Ipsum Dolor Sit Amet
     * @param {Number} eventId The event ID
     * @param {Number} userId The user ID
     * @param {module:api/FullSubscriptionApi~eventsFullSubscriptionPostCallback} callback The callback function, accepting three arguments: error, data, response
     */
    this.eventsFullSubscriptionPost = function(eventId, userId, callback) {
      var postBody = null;

      // verify the required parameter 'eventId' is set
      if (eventId === undefined || eventId === null) {
        throw new Error(
          "Missing the required parameter 'eventId' when calling eventsFullSubscriptionPost"
        );
      }

      // verify the required parameter 'userId' is set
      if (userId === undefined || userId === null) {
        throw new Error(
          "Missing the required parameter 'userId' when calling eventsFullSubscriptionPost"
        );
      }

      var pathParams = {};
      var queryParams = {
        eventId: eventId,
        userId: userId
      };
      var collectionQueryParams = {};
      var headerParams = {};
      var formParams = {};

      var authNames = [];
      var contentTypes = [];
      var accepts = [];
      var returnType = null;

      return this.apiClient.callApi(
        "/events/fullSubscription",
        "POST",
        pathParams,
        queryParams,
        collectionQueryParams,
        headerParams,
        formParams,
        postBody,
        authNames,
        contentTypes,
        accepts,
        returnType,
        callback
      );
    };
  };

  return exports;
});
