/**
 * Citibank Authenticator
 * Citibank Hackathon 2019 Authenticator
 *
 * OpenAPI spec version: 0.0.1
 * Contact: EMAIL
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.8
 *
 * Do not edit the class manually.
 *
 */

(function(factory) {
   if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('./ApiClient'), require('./model/Principal'), require('./model/User'), require('./api/HomeControllerApi'), require('./api/UserControllerApi'));
  }
}(function(ApiClient, Principal, User, HomeControllerApi, UserControllerApi) {
  'use strict';

  /**
   * Citibank_Hackathon_2019_Authenticator.<br>
   * The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
   * <p>
   * An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
   * <pre>
   * var CitibankAuthenticator = require('index'); // See note below*.
   * var xxxSvc = new CitibankAuthenticator.XxxApi(); // Allocate the API class we're going to use.
   * var yyyModel = new CitibankAuthenticator.Yyy(); // Construct a model instance.
   * yyyModel.someProperty = 'someValue';
   * ...
   * var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
   * ...
   * </pre>
   * <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
   * and put the application logic within the callback function.</em>
   * </p>
   * <p>
   * A non-AMD browser application (discouraged) might do something like this:
   * <pre>
   * var xxxSvc = new CitibankAuthenticator.XxxApi(); // Allocate the API class we're going to use.
   * var yyy = new CitibankAuthenticator.Yyy(); // Construct a model instance.
   * yyyModel.someProperty = 'someValue';
   * ...
   * var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
   * ...
   * </pre>
   * </p>
   * @module index
   * @version 0.0.1
   */
  var exports = {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient: ApiClient,
    /**
     * The Principal model constructor.
     * @property {module:model/Principal}
     */
    Principal: Principal,
    /**
     * The User model constructor.
     * @property {module:model/User}
     */
    User: User,
    /**
     * The HomeControllerApi service constructor.
     * @property {module:api/HomeControllerApi}
     */
    HomeControllerApi: HomeControllerApi,
    /**
     * The UserControllerApi service constructor.
     * @property {module:api/UserControllerApi}
     */
    UserControllerApi: UserControllerApi
  };

  return exports;
}));
