/**
 * Citibank EventHandler
 * Test description
 *
 * OpenAPI spec version: 0.0.1
 * Contact: contact@snippets.local
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.8
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
    if (typeof module === 'object' && module.exports) {
        // CommonJS-like environments that support module.exports, like Node.
        module.exports = factory(require('../ApiClient'));
    } else {
        // Browser globals (root is window)
        if (!root.CitibankEventHandler) {
            root.CitibankEventHandler = {};
        }
        root.CitibankEventHandler.CategorySerializers = factory(root.CitibankEventHandler.ApiClient);
    }
})(this, function(ApiClient) {
    'use strict';

    /**
     * The CategorySerializers model module.
     * @module model/CategorySerializers
     * @version 0.0.1
     */

    /**
     * Constructs a new <code>CategorySerializers</code>.
     * @alias module:model/CategorySerializers
     * @class
     * @param name {String}
     */
    var exports = function(name) {
        var _this = this;

        _this['name'] = name;
    };

    /**
     * Constructs a <code>CategorySerializers</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CategorySerializers} obj Optional instance to populate.
     * @return {module:model/CategorySerializers} The populated <code>CategorySerializers</code> instance.
     */
    exports.constructFromObject = function(data, obj) {
        if (data) {
            obj = obj || new exports();

            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
        }
        return obj;
    };

    /**
     * @member {String} name
     */
    exports.prototype['name'] = undefined;

    return exports;
});
