/**
 * Citibank EventHandler
 * Test description
 *
 * OpenAPI spec version: 0.0.1
 * Contact: contact@snippets.local
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.8
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof module === "object" && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require("../ApiClient"));
  } else {
    // Browser globals (root is window)
    if (!root.CitibankEventHandler) {
      root.CitibankEventHandler = {};
    }
    root.CitibankEventHandler.EventSerializers = factory(
      root.CitibankEventHandler.ApiClient
    );
  }
})(this, function(ApiClient) {
  "use strict";

  /**
   * The EventSerializers model module.
   * @module model/EventSerializers
   * @version 0.0.1
   */

  /**
   * Constructs a new <code>EventSerializers</code>.
   * @alias module:model/EventSerializers
   * @class
   * @param name {String}
   * @param startDateTime {Date}
   * @param descriptions {String}
   * @param status {Boolean}
   * @param organizerName {String}
   * @param category {Array.<String>}
   */
  var exports = function(
    name,
    startDateTime,
    descriptions,
    status,
    organizerName,
    category
  ) {
    var _this = this;

    _this["name"] = name;
    _this["start_date_time"] = startDateTime;

    _this["descriptions"] = descriptions;
    _this["status"] = status;
    _this["organizer_name"] = organizerName;
    _this["category"] = category;
  };

  /**
   * Constructs a <code>EventSerializers</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/EventSerializers} obj Optional instance to populate.
   * @return {module:model/EventSerializers} The populated <code>EventSerializers</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty("id")) {
        obj["id"] = ApiClient.convertToType(data["id"], "Number");
      }

      if (data.hasOwnProperty("url")) {
        obj["url"] = ApiClient.convertToType(data["url"], "String");
      }
      if (data.hasOwnProperty("name")) {
        obj["name"] = ApiClient.convertToType(data["name"], "String");
      }
      if (data.hasOwnProperty("start_date_time")) {
        obj["start_date_time"] = ApiClient.convertToType(
          data["start_date_time"],
          "Date"
        );
      }
      if (data.hasOwnProperty("max_participants")) {
        obj["max_participants"] = ApiClient.convertToType(
          data["max_participants"],
          "Number"
        );
      }
      if (data.hasOwnProperty("min_participants")) {
        obj["min_participants"] = ApiClient.convertToType(
          data["min_participants"],
          "Number"
        );
      }
      if (data.hasOwnProperty("descriptions")) {
        obj["descriptions"] = ApiClient.convertToType(
          data["descriptions"],
          "String"
        );
      }
      if (data.hasOwnProperty("status")) {
        obj["status"] = ApiClient.convertToType(data["status"], "Boolean");
      }
      if (data.hasOwnProperty("organizer_name")) {
        obj["organizer_name"] = ApiClient.convertToType(
          data["organizer_name"],
          "String"
        );
      }
      if (data.hasOwnProperty("category")) {
        obj["category"] = ApiClient.convertToType(data["category"], ["String"]);
      }
    }
    return obj;
  };

  /**
   * @member {String} url
   */
  exports.prototype["url"] = undefined;
  /**
   * @member {String} name
   */
  exports.prototype["name"] = undefined;
  /**
   * @member {Date} start_date_time
   */
  exports.prototype["start_date_time"] = undefined;
  /**
   * @member {Number} max_participants
   */
  exports.prototype["max_participants"] = undefined;
  /**
   * @member {Number} min_participants
   */
  exports.prototype["min_participants"] = undefined;
  /**
   * @member {String} descriptions
   */
  exports.prototype["descriptions"] = undefined;
  /**
   * @member {Boolean} status
   */
  exports.prototype["status"] = undefined;
  /**
   * @member {String} organizer_name
   */
  exports.prototype["organizer_name"] = undefined;
  /**
   * @member {Array.<String>} category
   */
  exports.prototype["category"] = undefined;

  return exports;
});
