/**
 * Citibank EventHandler
 * Test description
 *
 * OpenAPI spec version: 0.0.1
 * Contact: contact@snippets.local
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.8
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
    if (typeof module === 'object' && module.exports) {
        // CommonJS-like environments that support module.exports, like Node.
        module.exports = factory(require('../ApiClient'));
    } else {
        // Browser globals (root is window)
        if (!root.CitibankEventHandler) {
            root.CitibankEventHandler = {};
        }
        root.CitibankEventHandler.RegisterSerializers = factory(root.CitibankEventHandler.ApiClient);
    }
})(this, function(ApiClient) {
    'use strict';

    /**
     * The RegisterSerializers model module.
     * @module model/RegisterSerializers
     * @version 0.0.1
     */

    /**
     * Constructs a new <code>RegisterSerializers</code>.
     * @alias module:model/RegisterSerializers
     * @class
     * @param participantId {Number}
     * @param attendance {Boolean}
     * @param feedback {String}
     * @param eventId {String}
     */
    var exports = function(participantId, attendance, feedback, eventId) {
        var _this = this;

        _this['participant_id'] = participantId;
        _this['attendance'] = attendance;
        _this['feedback'] = feedback;
        _this['event_id'] = eventId;
    };

    /**
     * Constructs a <code>RegisterSerializers</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/RegisterSerializers} obj Optional instance to populate.
     * @return {module:model/RegisterSerializers} The populated <code>RegisterSerializers</code> instance.
     */
    exports.constructFromObject = function(data, obj) {
        if (data) {
            obj = obj || new exports();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('url')) {
                obj['url'] = ApiClient.convertToType(data['url'], 'String');
            }
            if (data.hasOwnProperty('participant_id')) {
                obj['participant_id'] = ApiClient.convertToType(data['participant_id'], 'Number');
            }
            if (data.hasOwnProperty('attendance')) {
                obj['attendance'] = ApiClient.convertToType(data['attendance'], 'Boolean');
            }
            if (data.hasOwnProperty('feedback')) {
                obj['feedback'] = ApiClient.convertToType(data['feedback'], 'String');
            }
            if (data.hasOwnProperty('event_id')) {
                obj['event_id'] = ApiClient.convertToType(data['event_id'], 'String');
            }
        }
        return obj;
    };

    /**
     * @member {String} url
     */
    exports.prototype['url'] = undefined;
    /**
     * @member {Number} participant_id
     */
    exports.prototype['participant_id'] = undefined;
    /**
     * @member {Boolean} attendance
     */
    exports.prototype['attendance'] = undefined;
    /**
     * @member {String} feedback
     */
    exports.prototype['feedback'] = undefined;
    /**
     * @member {String} event_id
     */
    exports.prototype['event_id'] = undefined;

    return exports;
});
