/**
 * Citibank EventHandler
 * Test description
 *
 * OpenAPI spec version: 0.0.1
 * Contact: contact@snippets.local
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.8
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
    if (typeof module === 'object' && module.exports) {
        // CommonJS-like environments that support module.exports, like Node.
        factory(require('expect.js'), require('../../src/index'));
    } else {
        // Browser globals (root is window)
        factory(root.expect, root.CitibankEventHandler);
    }
})(this, function(expect, CitibankEventHandler) {
    'use strict';

    var instance;

    beforeEach(function() {
        instance = new CitibankEventHandler.EventSerializers();
    });

    var getProperty = function(object, getter, property) {
        // Use getter method if present; otherwise, get the property directly.
        if (typeof object[getter] === 'function') return object[getter]();
        else return object[property];
    };

    var setProperty = function(object, setter, property, value) {
        // Use setter method if present; otherwise, set the property directly.
        if (typeof object[setter] === 'function') object[setter](value);
        else object[property] = value;
    };

    describe('EventSerializers', function() {
        it('should create an instance of EventSerializers', function() {
            // uncomment below and update the code to test EventSerializers
            //var instance = new CitibankEventHandler.EventSerializers();
            //expect(instance).to.be.a(CitibankEventHandler.EventSerializers);
        });

        it('should have the property url (base name: "url")', function() {
            // uncomment below and update the code to test the property url
            //var instance = new CitibankEventHandler.EventSerializers();
            //expect(instance).to.be();
        });

        it('should have the property name (base name: "name")', function() {
            // uncomment below and update the code to test the property name
            //var instance = new CitibankEventHandler.EventSerializers();
            //expect(instance).to.be();
        });

        it('should have the property startDateTime (base name: "start_date_time")', function() {
            // uncomment below and update the code to test the property startDateTime
            //var instance = new CitibankEventHandler.EventSerializers();
            //expect(instance).to.be();
        });

        it('should have the property maxParticipants (base name: "max_participants")', function() {
            // uncomment below and update the code to test the property maxParticipants
            //var instance = new CitibankEventHandler.EventSerializers();
            //expect(instance).to.be();
        });

        it('should have the property minParticipants (base name: "min_participants")', function() {
            // uncomment below and update the code to test the property minParticipants
            //var instance = new CitibankEventHandler.EventSerializers();
            //expect(instance).to.be();
        });

        it('should have the property descriptions (base name: "descriptions")', function() {
            // uncomment below and update the code to test the property descriptions
            //var instance = new CitibankEventHandler.EventSerializers();
            //expect(instance).to.be();
        });

        it('should have the property status (base name: "status")', function() {
            // uncomment below and update the code to test the property status
            //var instance = new CitibankEventHandler.EventSerializers();
            //expect(instance).to.be();
        });

        it('should have the property organizerName (base name: "organizer_name")', function() {
            // uncomment below and update the code to test the property organizerName
            //var instance = new CitibankEventHandler.EventSerializers();
            //expect(instance).to.be();
        });

        it('should have the property category (base name: "category")', function() {
            // uncomment below and update the code to test the property category
            //var instance = new CitibankEventHandler.EventSerializers();
            //expect(instance).to.be();
        });
    });
});
