/**
 * Citibank EventHandler
 * Test description
 *
 * OpenAPI spec version: 0.0.1
 * Contact: contact@snippets.local
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.8
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
    if (typeof module === 'object' && module.exports) {
        // CommonJS-like environments that support module.exports, like Node.
        factory(require('expect.js'), require('../../src/index'));
    } else {
        // Browser globals (root is window)
        factory(root.expect, root.CitibankEventHandler);
    }
})(this, function(expect, CitibankEventHandler) {
    'use strict';

    var instance;

    beforeEach(function() {
        instance = new CitibankEventHandler.RegisterSerializers();
    });

    var getProperty = function(object, getter, property) {
        // Use getter method if present; otherwise, get the property directly.
        if (typeof object[getter] === 'function') return object[getter]();
        else return object[property];
    };

    var setProperty = function(object, setter, property, value) {
        // Use setter method if present; otherwise, set the property directly.
        if (typeof object[setter] === 'function') object[setter](value);
        else object[property] = value;
    };

    describe('RegisterSerializers', function() {
        it('should create an instance of RegisterSerializers', function() {
            // uncomment below and update the code to test RegisterSerializers
            //var instance = new CitibankEventHandler.RegisterSerializers();
            //expect(instance).to.be.a(CitibankEventHandler.RegisterSerializers);
        });

        it('should have the property url (base name: "url")', function() {
            // uncomment below and update the code to test the property url
            //var instance = new CitibankEventHandler.RegisterSerializers();
            //expect(instance).to.be();
        });

        it('should have the property participantId (base name: "participant_id")', function() {
            // uncomment below and update the code to test the property participantId
            //var instance = new CitibankEventHandler.RegisterSerializers();
            //expect(instance).to.be();
        });

        it('should have the property attendance (base name: "attendance")', function() {
            // uncomment below and update the code to test the property attendance
            //var instance = new CitibankEventHandler.RegisterSerializers();
            //expect(instance).to.be();
        });

        it('should have the property feedback (base name: "feedback")', function() {
            // uncomment below and update the code to test the property feedback
            //var instance = new CitibankEventHandler.RegisterSerializers();
            //expect(instance).to.be();
        });

        it('should have the property eventId (base name: "event_id")', function() {
            // uncomment below and update the code to test the property eventId
            //var instance = new CitibankEventHandler.RegisterSerializers();
            //expect(instance).to.be();
        });
    });
});
