/**
 * Citibank Reporting
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.8
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
    if (typeof module === 'object' && module.exports) {
        // CommonJS-like environments that support module.exports, like Node.
        factory(require('expect.js'), require('../../src/index'));
    } else {
        // Browser globals (root is window)
        factory(root.expect, root.CitibankReporting);
    }
})(this, function(expect, CitibankReporting) {
    'use strict';

    var instance;

    beforeEach(function() {
        instance = new CitibankReporting.DefaultApi();
    });

    var getProperty = function(object, getter, property) {
        // Use getter method if present; otherwise, get the property directly.
        if (typeof object[getter] === 'function') return object[getter]();
        else return object[property];
    };

    var setProperty = function(object, setter, property, value) {
        // Use setter method if present; otherwise, set the property directly.
        if (typeof object[setter] === 'function') object[setter](value);
        else object[property] = value;
    };

    describe('DefaultApi', function() {
        describe('getDemographicApi', function() {
            it('should call getDemographicApi successfully', function(done) {
                //uncomment below and update the code to test getDemographicApi
                //instance.getDemographicApi(function(error) {
                //  if (error) throw error;
                //expect().to.be();
                //});
                done();
            });
        });
        describe('getHistoricalApi', function() {
            it('should call getHistoricalApi successfully', function(done) {
                //uncomment below and update the code to test getHistoricalApi
                //instance.getHistoricalApi(function(error) {
                //  if (error) throw error;
                //expect().to.be();
                //});
                done();
            });
        });
        describe('getOrganizationApi', function() {
            it('should call getOrganizationApi successfully', function(done) {
                //uncomment below and update the code to test getOrganizationApi
                //instance.getOrganizationApi(function(error) {
                //  if (error) throw error;
                //expect().to.be();
                //});
                done();
            });
        });
        describe('getUserHistoricalApi', function() {
            it('should call getUserHistoricalApi successfully', function(done) {
                //uncomment below and update the code to test getUserHistoricalApi
                //instance.getUserHistoricalApi(function(error) {
                //  if (error) throw error;
                //expect().to.be();
                //});
                done();
            });
        });
    });
});
