/**
 * Citibank EventHandler
 * Test description
 *
 * OpenAPI spec version: 0.0.1
 * Contact: contact@snippets.local
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.8
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
    if (typeof module === 'object' && module.exports) {
        // CommonJS-like environments that support module.exports, like Node.
        factory(require('expect.js'), require('../../src/index'));
    } else {
        // Browser globals (root is window)
        factory(root.expect, root.CitibankEventHandler);
    }
})(this, function(expect, CitibankEventHandler) {
    'use strict';

    var instance;

    beforeEach(function() {
        instance = new CitibankEventHandler.CategoriesApi();
    });

    var getProperty = function(object, getter, property) {
        // Use getter method if present; otherwise, get the property directly.
        if (typeof object[getter] === 'function') return object[getter]();
        else return object[property];
    };

    var setProperty = function(object, setter, property, value) {
        // Use setter method if present; otherwise, set the property directly.
        if (typeof object[setter] === 'function') object[setter](value);
        else object[property] = value;
    };

    describe('CategoriesApi', function() {
        describe('categoriesCreate', function() {
            it('should call categoriesCreate successfully', function(done) {
                //uncomment below and update the code to test categoriesCreate
                //instance.categoriesCreate(function(error) {
                //  if (error) throw error;
                //expect().to.be();
                //});
                done();
            });
        });
        describe('categoriesDelete', function() {
            it('should call categoriesDelete successfully', function(done) {
                //uncomment below and update the code to test categoriesDelete
                //instance.categoriesDelete(function(error) {
                //  if (error) throw error;
                //expect().to.be();
                //});
                done();
            });
        });
        describe('categoriesList', function() {
            it('should call categoriesList successfully', function(done) {
                //uncomment below and update the code to test categoriesList
                //instance.categoriesList(function(error) {
                //  if (error) throw error;
                //expect().to.be();
                //});
                done();
            });
        });
        describe('categoriesPartialUpdate', function() {
            it('should call categoriesPartialUpdate successfully', function(done) {
                //uncomment below and update the code to test categoriesPartialUpdate
                //instance.categoriesPartialUpdate(function(error) {
                //  if (error) throw error;
                //expect().to.be();
                //});
                done();
            });
        });
        describe('categoriesRead', function() {
            it('should call categoriesRead successfully', function(done) {
                //uncomment below and update the code to test categoriesRead
                //instance.categoriesRead(function(error) {
                //  if (error) throw error;
                //expect().to.be();
                //});
                done();
            });
        });
        describe('categoriesUpdate', function() {
            it('should call categoriesUpdate successfully', function(done) {
                //uncomment below and update the code to test categoriesUpdate
                //instance.categoriesUpdate(function(error) {
                //  if (error) throw error;
                //expect().to.be();
                //});
                done();
            });
        });
    });
});
