/**
 * Citibank EventHandler
 * Test description
 *
 * OpenAPI spec version: 0.0.1
 * Contact: contact@snippets.local
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.8
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
    if (typeof module === 'object' && module.exports) {
        // CommonJS-like environments that support module.exports, like Node.
        factory(require('expect.js'), require('../../src/index'));
    } else {
        // Browser globals (root is window)
        factory(root.expect, root.CitibankEventHandler);
    }
})(this, function(expect, CitibankEventHandler) {
    'use strict';

    var instance;

    beforeEach(function() {
        instance = new CitibankEventHandler.RegisterApi();
    });

    var getProperty = function(object, getter, property) {
        // Use getter method if present; otherwise, get the property directly.
        if (typeof object[getter] === 'function') return object[getter]();
        else return object[property];
    };

    var setProperty = function(object, setter, property, value) {
        // Use setter method if present; otherwise, set the property directly.
        if (typeof object[setter] === 'function') object[setter](value);
        else object[property] = value;
    };

    describe('RegisterApi', function() {
        describe('registerCreate', function() {
            it('should call registerCreate successfully', function(done) {
                //uncomment below and update the code to test registerCreate
                //instance.registerCreate(function(error) {
                //  if (error) throw error;
                //expect().to.be();
                //});
                done();
            });
        });
        describe('registerDelete', function() {
            it('should call registerDelete successfully', function(done) {
                //uncomment below and update the code to test registerDelete
                //instance.registerDelete(function(error) {
                //  if (error) throw error;
                //expect().to.be();
                //});
                done();
            });
        });
        describe('registerList', function() {
            it('should call registerList successfully', function(done) {
                //uncomment below and update the code to test registerList
                //instance.registerList(function(error) {
                //  if (error) throw error;
                //expect().to.be();
                //});
                done();
            });
        });
        describe('registerPartialUpdate', function() {
            it('should call registerPartialUpdate successfully', function(done) {
                //uncomment below and update the code to test registerPartialUpdate
                //instance.registerPartialUpdate(function(error) {
                //  if (error) throw error;
                //expect().to.be();
                //});
                done();
            });
        });
        describe('registerRead', function() {
            it('should call registerRead successfully', function(done) {
                //uncomment below and update the code to test registerRead
                //instance.registerRead(function(error) {
                //  if (error) throw error;
                //expect().to.be();
                //});
                done();
            });
        });
        describe('registerUpdate', function() {
            it('should call registerUpdate successfully', function(done) {
                //uncomment below and update the code to test registerUpdate
                //instance.registerUpdate(function(error) {
                //  if (error) throw error;
                //expect().to.be();
                //});
                done();
            });
        });
    });
});
