/**
 * Citibank Authenticator
 * Citibank Hackathon 2019 Authenticator
 *
 * OpenAPI spec version: 0.0.1
 * Contact: EMAIL
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.8
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
   if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.CitibankAuthenticator);
  }
}(this, function(expect, CitibankAuthenticator) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new CitibankAuthenticator.UserControllerApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('UserControllerApi', function() {
    describe('createNewUserUsingPOST', function() {
      it('should call createNewUserUsingPOST successfully', function(done) {
        //uncomment below and update the code to test createNewUserUsingPOST
        //instance.createNewUserUsingPOST(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deleteUserUsingDELETE', function() {
      it('should call deleteUserUsingDELETE successfully', function(done) {
        //uncomment below and update the code to test deleteUserUsingDELETE
        //instance.deleteUserUsingDELETE(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('findUserByIdUsingGET', function() {
      it('should call findUserByIdUsingGET successfully', function(done) {
        //uncomment below and update the code to test findUserByIdUsingGET
        //instance.findUserByIdUsingGET(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('registerNewUserUsingPOST', function() {
      it('should call registerNewUserUsingPOST successfully', function(done) {
        //uncomment below and update the code to test registerNewUserUsingPOST
        //instance.registerNewUserUsingPOST(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('resetPasswordUsingGET', function() {
      it('should call resetPasswordUsingGET successfully', function(done) {
        //uncomment below and update the code to test resetPasswordUsingGET
        //instance.resetPasswordUsingGET(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('updateAccDetailUsingPUT', function() {
      it('should call updateAccDetailUsingPUT successfully', function(done) {
        //uncomment below and update the code to test updateAccDetailUsingPUT
        //instance.updateAccDetailUsingPUT(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('updateAccTypeUsingPUT', function() {
      it('should call updateAccTypeUsingPUT successfully', function(done) {
        //uncomment below and update the code to test updateAccTypeUsingPUT
        //instance.updateAccTypeUsingPUT(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('userUsingGET', function() {
      it('should call userUsingGET successfully', function(done) {
        //uncomment below and update the code to test userUsingGET
        //instance.userUsingGET(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
