/**
 * Citibank EventHandler
 * Test description
 *
 * OpenAPI spec version: 0.0.1
 * Contact: contact@snippets.local
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.8
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
    if (typeof module === 'object' && module.exports) {
        // CommonJS-like environments that support module.exports, like Node.
        module.exports = factory(require('../ApiClient'), require('../model/RegisterSerializers'));
    } else {
        // Browser globals (root is window)
        if (!root.CitibankEventHandler) {
            root.CitibankEventHandler = {};
        }
        root.CitibankEventHandler.RegisterApi = factory(
            root.CitibankEventHandler.ApiClient,
            root.CitibankEventHandler.RegisterSerializers,
        );
    }
})(this, function(ApiClient, RegisterSerializers) {
    'use strict';

    /**
     * Register service.
     * @module api/RegisterApi
     * @version 0.0.1
     */

    /**
     * Constructs a new RegisterApi.
     * @alias module:api/RegisterApi
     * @class
     * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
     * default to {@link module:ApiClient#instance} if unspecified.
     */
    var exports = function(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;

        /**
         * Callback function to receive the result of the registerCreate operation.
         * @callback module:api/RegisterApi~registerCreateCallback
         * @param {String} error Error message, if any.
         * @param {module:model/RegisterSerializers} data The data returned by the service call.
         * @param {String} response The complete HTTP response.
         */

        /**
         *
         * @param {module:model/RegisterSerializers} data
         * @param {module:api/RegisterApi~registerCreateCallback} callback The callback function, accepting three arguments: error, data, response
         * data is of type: {@link module:model/RegisterSerializers}
         */
        this.registerCreate = function(data, callback) {
            var postBody = data;

            // verify the required parameter 'data' is set
            if (data === undefined || data === null) {
                throw new Error("Missing the required parameter 'data' when calling registerCreate");
            }

            var pathParams = {};
            var queryParams = {};
            var collectionQueryParams = {};
            var headerParams = {};
            var formParams = {};

            var authNames = ['Basic'];
            var contentTypes = ['application/json'];
            var accepts = ['application/json'];
            var returnType = RegisterSerializers;

            return this.apiClient.callApi(
                '/registers/',
                'POST',
                pathParams,
                queryParams,
                collectionQueryParams,
                headerParams,
                formParams,
                postBody,
                authNames,
                contentTypes,
                accepts,
                returnType,
                callback,
            );
        };

        /**
         * Callback function to receive the result of the registerDelete operation.
         * @callback module:api/RegisterApi~registerDeleteCallback
         * @param {String} error Error message, if any.
         * @param data This operation does not return a value.
         * @param {String} response The complete HTTP response.
         */

        /**
         *
         * @param {Number} id A unique integer value identifying this register.
         * @param {module:api/RegisterApi~registerDeleteCallback} callback The callback function, accepting three arguments: error, data, response
         */
        this.registerDelete = function(id, callback) {
            var postBody = null;

            // verify the required parameter 'id' is set
            if (id === undefined || id === null) {
                throw new Error("Missing the required parameter 'id' when calling registerDelete");
            }

            var pathParams = {
                id: id,
            };
            var queryParams = {};
            var collectionQueryParams = {};
            var headerParams = {};
            var formParams = {};

            var authNames = ['Basic'];
            var contentTypes = ['application/json'];
            var accepts = ['application/json'];
            var returnType = null;

            return this.apiClient.callApi(
                '/registers/{id}/',
                'DELETE',
                pathParams,
                queryParams,
                collectionQueryParams,
                headerParams,
                formParams,
                postBody,
                authNames,
                contentTypes,
                accepts,
                returnType,
                callback,
            );
        };

        /**
         * Callback function to receive the result of the registerList operation.
         * @callback module:api/RegisterApi~registerListCallback
         * @param {String} error Error message, if any.
         * @param {Array.<module:model/RegisterSerializers>} data The data returned by the service call.
         * @param {String} response The complete HTTP response.
         */

        /**
         *
         * @param {module:api/RegisterApi~registerListCallback} callback The callback function, accepting three arguments: error, data, response
         * data is of type: {@link Array.<module:model/RegisterSerializers>}
         */
        this.registerList = function(callback) {
            var postBody = null;

            var pathParams = {};
            var queryParams = {};
            var collectionQueryParams = {};
            var headerParams = {};
            var formParams = {};

            var authNames = ['Basic'];
            var contentTypes = ['application/json'];
            var accepts = ['application/json'];
            var returnType = [RegisterSerializers];

            return this.apiClient.callApi(
                '/registers/',
                'GET',
                pathParams,
                queryParams,
                collectionQueryParams,
                headerParams,
                formParams,
                postBody,
                authNames,
                contentTypes,
                accepts,
                returnType,
                callback,
            );
        };

        /**
         * Callback function to receive the result of the registerPartialUpdate operation.
         * @callback module:api/RegisterApi~registerPartialUpdateCallback
         * @param {String} error Error message, if any.
         * @param {module:model/RegisterSerializers} data The data returned by the service call.
         * @param {String} response The complete HTTP response.
         */

        /**
         *
         * @param {Number} id A unique integer value identifying this register.
         * @param {module:model/RegisterSerializers} data
         * @param {module:api/RegisterApi~registerPartialUpdateCallback} callback The callback function, accepting three arguments: error, data, response
         * data is of type: {@link module:model/RegisterSerializers}
         */
        this.registerPartialUpdate = function(id, data, callback) {
            var postBody = data;

            // verify the required parameter 'id' is set
            if (id === undefined || id === null) {
                throw new Error("Missing the required parameter 'id' when calling registerPartialUpdate");
            }

            // verify the required parameter 'data' is set
            if (data === undefined || data === null) {
                throw new Error("Missing the required parameter 'data' when calling registerPartialUpdate");
            }

            var pathParams = {
                id: id,
            };
            var queryParams = {};
            var collectionQueryParams = {};
            var headerParams = {};
            var formParams = {};

            var authNames = ['Basic'];
            var contentTypes = ['application/json'];
            var accepts = ['application/json'];
            var returnType = RegisterSerializers;

            return this.apiClient.callApi(
                '/registers/{id}/',
                'PATCH',
                pathParams,
                queryParams,
                collectionQueryParams,
                headerParams,
                formParams,
                postBody,
                authNames,
                contentTypes,
                accepts,
                returnType,
                callback,
            );
        };

        /**
         * Callback function to receive the result of the registerRead operation.
         * @callback module:api/RegisterApi~registerReadCallback
         * @param {String} error Error message, if any.
         * @param {module:model/RegisterSerializers} data The data returned by the service call.
         * @param {String} response The complete HTTP response.
         */

        /**
         *
         * @param {Number} id A unique integer value identifying this register.
         * @param {module:api/RegisterApi~registerReadCallback} callback The callback function, accepting three arguments: error, data, response
         * data is of type: {@link module:model/RegisterSerializers}
         */
        this.registerRead = function(id, callback) {
            var postBody = null;

            // verify the required parameter 'id' is set
            if (id === undefined || id === null) {
                throw new Error("Missing the required parameter 'id' when calling registerRead");
            }

            var pathParams = {
                id: id,
            };
            var queryParams = {};
            var collectionQueryParams = {};
            var headerParams = {};
            var formParams = {};

            var authNames = ['Basic'];
            var contentTypes = ['application/json'];
            var accepts = ['application/json'];
            var returnType = RegisterSerializers;

            return this.apiClient.callApi(
                '/registers/{id}/',
                'GET',
                pathParams,
                queryParams,
                collectionQueryParams,
                headerParams,
                formParams,
                postBody,
                authNames,
                contentTypes,
                accepts,
                returnType,
                callback,
            );
        };

        /**
         * Callback function to receive the result of the registerUpdate operation.
         * @callback module:api/RegisterApi~registerUpdateCallback
         * @param {String} error Error message, if any.
         * @param {module:model/RegisterSerializers} data The data returned by the service call.
         * @param {String} response The complete HTTP response.
         */

        /**
         *
         * @param {Number} id A unique integer value identifying this register.
         * @param {module:model/RegisterSerializers} data
         * @param {module:api/RegisterApi~registerUpdateCallback} callback The callback function, accepting three arguments: error, data, response
         * data is of type: {@link module:model/RegisterSerializers}
         */
        this.registerUpdate = function(id, data, callback) {
            var postBody = data;

            // verify the required parameter 'id' is set
            if (id === undefined || id === null) {
                throw new Error("Missing the required parameter 'id' when calling registerUpdate");
            }

            // verify the required parameter 'data' is set
            if (data === undefined || data === null) {
                throw new Error("Missing the required parameter 'data' when calling registerUpdate");
            }

            var pathParams = {
                id: id,
            };
            var queryParams = {};
            var collectionQueryParams = {};
            var headerParams = {};
            var formParams = {};

            var authNames = ['Basic'];
            var contentTypes = ['application/json'];
            var accepts = ['application/json'];
            var returnType = RegisterSerializers;

            return this.apiClient.callApi(
                '/registers/{id}/',
                'PUT',
                pathParams,
                queryParams,
                collectionQueryParams,
                headerParams,
                formParams,
                postBody,
                authNames,
                contentTypes,
                accepts,
                returnType,
                callback,
            );
        };
    };

    return exports;
});
