/**
 * Citibank Communicator
 * Email Notifications Sender
 *
 * OpenAPI spec version: 0.0.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.8
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof module === "object" && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require("expect.js"), require("../../src/index"));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.CitibankCommunicator);
  }
})(this, function(expect, CitibankCommunicator) {
  "use strict";

  var instance;

  beforeEach(function() {
    instance = new CitibankCommunicator.UpcomingEventSubscriptionApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === "function") return object[getter]();
    else return object[property];
  };

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === "function") object[setter](value);
    else object[property] = value;
  };

  describe("UpcomingEventSubscriptionApi", function() {
    describe("eventsUpcomingEventSubscriptionDelete", function() {
      it("should call eventsUpcomingEventSubscriptionDelete successfully", function(done) {
        //uncomment below and update the code to test eventsUpcomingEventSubscriptionDelete
        //instance.eventsUpcomingEventSubscriptionDelete(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe("eventsUpcomingEventSubscriptionPost", function() {
      it("should call eventsUpcomingEventSubscriptionPost successfully", function(done) {
        //uncomment below and update the code to test eventsUpcomingEventSubscriptionPost
        //instance.eventsUpcomingEventSubscriptionPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });
});
